import { Vocabulary } from "../types";

export const engineeringVocabularyArray: Vocabulary[] = [
    {
      en: "engineering",
      bn: "প্রকৌশল",
      category: "engineering",
      explanation: "The branch of science and technology concerned with the design, building, and use of engines, machines, and structures.",
      example: "Engineering involves applying scientific principles to solve practical problems.",
    },
    {
      en: "mechanical",
      bn: "যান্ত্রিক",
      category: "engineering",
      explanation: "Relating to machines or machinery.",
      example: "Mechanical engineers design and build mechanical systems.",
    },
    {
      en: "civil",
      bn: "নাগরিক",
      category: "engineering",
      explanation: "Relating to the design, construction, and maintenance of public works such as roads, bridges, and buildings.",
      example: "Civil engineering projects improve infrastructure.",
    },
    {
      en: "electrical",
      bn: "বৈদ্যুতিন",
      category: "engineering",
      explanation: "Relating to electricity or the use of electrical power.",
      example: "Electrical engineers work with electrical systems and devices.",
    },
    {
      en: "electronics",
      bn: "ইলেকট্রনিক্স",
      category: "engineering",
      explanation: "The branch of physics and technology concerned with the design of circuits using transistors and microchips, and with the behavior and movement of electrons in a semiconductor, conductor, vacuum, or gas.",
      example: "Electronics has revolutionized communication and computing.",
    },
    {
      en: "computer science",
      bn: "কম্পিউটার বিজ্ঞান",
      category: "engineering",
      explanation: "The study of the principles and use of computers.",
      example: "Computer scientists develop software and algorithms.",
    },
    {
      en: "software",
      bn: "সফটওয়্যার",
      category: "engineering",
      explanation: "Programs and operating information used by a computer.",
      example: "Software engineers develop applications and operating systems.",
    },
    {
      en: "mechatronics",
      bn: "মেকাট্রনিক্স",
      category: "engineering",
      explanation: "The combination of mechanical engineering, electronic engineering, and software engineering.",
      example: "Mechatronics involves designing intelligent systems.",
    },
    {
      en: "biomedical",
      bn: "বায়োমেডিক্যাল",
      category: "engineering",
      explanation: "Relating to the application of engineering principles and techniques to medical and biological problems.",
      example: "Biomedical engineers develop medical devices and equipment.",
    },
    {
      en: "aerospace",
      bn: "এয়রোস্পেস",
      category: "engineering",
      explanation: "Relating to the design and production of aircraft, spacecraft, and related systems and equipment.",
      example: "Aerospace engineering involves designing airplanes and rockets.",
    },
    {
      en: "chemical",
      bn: "রাসায়নিক",
      category: "engineering",
      explanation: "Relating to or used in chemistry or its applications.",
      example: "Chemical engineers work with chemicals and chemical processes.",
    },
    {
      en: "environmental",
      bn: "পরিবেশ",
      category: "engineering",
      explanation: "Relating to the environment and the impact of human activity on it.",
      example: "Environmental engineers work on projects to protect the environment.",
    },
    {
      en: "biotechnology",
      bn: "জৈবপ্রযুক্তি",
      category: "engineering",
      explanation: "The exploitation of biological processes for industrial and other purposes, especially the genetic manipulation of microorganisms for the production of antibiotics, hormones, etc.",
      example: "Biotechnology involves using biological systems to develop new products.",
    },
    {
      en: "structural",
      bn: "কাঠামো",
      category: "engineering",
      explanation: "Relating to the structure of buildings, bridges, etc.",
      example: "Structural engineers design strong and stable structures.",
    },
    {
      en: "telecommunications",
      bn: "টেলিকমিউনিকেশনস",
      category: "engineering",
      explanation: "The transmission of information over significant distances to communicate.",
      example: "Telecommunications engineers develop networks for phone and internet communication.",
    },
    {
      en: "robotics",
      bn: "রোবটিক্স",
      category: "engineering",
      explanation: "The branch of technology that deals with the design, construction, operation, and application of robots.",
      example: "Robotics involves programming and controlling robotic systems.",
    },
    {
      en: "nanotechnology",
      bn: "ন্যানোটেকনোলজি",
      category: "engineering",
      explanation: "The branch of technology that deals with dimensions and tolerances of less than 100 nanometers, especially the manipulation of individual atoms and molecules.",
      example: "Nanotechnology has applications in medicine and materials science.",
    },
    {
      en: "automation",
      bn: "স্বয়ংক্রিয়করণ",
      category: "engineering",
      explanation: "The use of control systems and information technologies to reduce the need for human work in the production of goods and services.",
      example: "Automation improves efficiency in manufacturing processes.",
    },
    {
      en: "energy",
      bn: "শক্তি",
      category: "engineering",
      explanation: "The capacity of a physical system to perform work.",
      example: "Energy engineers work on sustainable energy solutions.",
    },
    {
      en: "sustainability",
      bn: "টেকসইত্ব",
      category: "engineering",
      explanation: "The ability to maintain a certain level of balance or efficiency over time.",
      example: "Sustainability is a key consideration in modern engineering projects.",
    },
  ];
  