import { Vocabulary } from "../types";

export const foodAndNutritionVocabularyArray: Vocabulary[] = [
    {
      en: "nutrition",
      bn: "পুষ্টি",
      category: "food",
      explanation: "The process of providing or obtaining the food necessary for health and growth.",
      example: "Good nutrition is essential for a healthy lifestyle.",
      partsOfSpeech: "noun",
    },
    {
      en: "food",
      bn: "খাদ্য",
      category: "food",
      explanation: "Any nutritious substance that people or animals eat or drink in order to maintain life and growth.",
      example: "They enjoyed delicious food at the restaurant.",
      partsOfSpeech: "noun",
    },
    {
      en: "diet",
      bn: "ডায়েট",
      category: "food",
      explanation: "The kinds of food that a person, animal, or community habitually eats.",
      example: "She follows a strict diet to stay healthy.",
      partsOfSpeech: "noun",
    },
    {
      en: "calorie",
      bn: "ক্যালোরি",
      category: "food",
      explanation: "A unit of energy that is equal to the amount of heat needed to raise the temperature of one kilogram of water by one degree Celsius.",
      example: "The nutrition label shows the calorie content of the food.",
      partsOfSpeech: "noun",
    },
    {
      en: "protein",
      bn: "প্রোটিন",
      category: "food",
      explanation: "A nutrient that is essential for growth and repair of tissues in the body.",
      example: "Fish and chicken are good sources of protein.",
      partsOfSpeech: "noun",
    },
    {
      en: "carbohydrate",
      bn: "কার্বোহাইড্রেট",
      category: "food",
      explanation: "A biological molecule consisting of carbon, hydrogen, and oxygen atoms, usually with a hydrogen–oxygen atom ratio of 2:1.",
      example: "Bread and pasta are rich in carbohydrates.",
      partsOfSpeech: "noun",
    },
    {
      en: "fat",
      bn: "চর্বি",
      category: "food",
      explanation: "A natural oily or greasy substance occurring in animal bodies, especially when deposited as a layer under the skin or around certain organs.",
      example: "Avocado and nuts contain healthy fats.",
      partsOfSpeech: "noun",
    },
    {
      en: "vitamin",
      bn: "ভিটামিন",
      category: "food",
      explanation: "Any of a group of organic compounds that are essential for normal growth and nutrition and are required in small quantities in the diet.",
      example: "Fruits and vegetables are rich in vitamins.",
      partsOfSpeech: "noun",
    },
    {
      en: "mineral",
      bn: "খনিজ",
      category: "food",
      explanation: "A solid, naturally occurring inorganic substance.",
      example: "Calcium and iron are important minerals for the body.",
      partsOfSpeech: "noun",
    },
    {
      en: "fiber",
      bn: "ফাইবার",
      category: "food",
      explanation: "A thread or filament from which a vegetable tissue, mineral substance, or textile is formed.",
      example: "Whole grains and fruits are high in dietary fiber.",
      partsOfSpeech: "noun",
    },
    {
      en: "nutrient",
      bn: "পুষ্টিতত্ত্ব",
      category: "food",
      explanation: "A substance that provides nourishment essential for growth and the maintenance of life.",
      example: "Proteins, carbohydrates, and fats are essential nutrients.",
      partsOfSpeech: "noun",
    },
    {
      en: "organic",
      bn: "জৈব",
      category: "food",
      explanation: "Relating to or derived from living matter.",
      example: "They prefer to buy organic fruits and vegetables.",
      partsOfSpeech: "adjective",
    },
    {
      en: "fresh",
      bn: "তাজা",
      category: "food",
      explanation: "Recently made or obtained; not canned, frozen, or preserved.",
      example: "They bought fresh fish from the market.",
      partsOfSpeech: "adjective",
    },
    {
      en: "processed",
      bn: "প্রসেসড",
      category: "food",
      explanation: "Subjected to a special process or treatment, especially in order to improve its keeping quality or taste.",
      example: "They avoid processed foods with additives.",
      partsOfSpeech: "adjective",
    },
    {
      en: "balanced",
      bn: "তালিকা",
      category: "food",
      explanation: "Having different elements in the correct proportions.",
      example: "A balanced diet includes a variety of foods.",
      partsOfSpeech: "adjective",
    },
    {
      en: "nutritious",
      bn: "পুষ্টিকর",
      category: "food",
      explanation: "Providing nourishment; nourishing.",
      example: "They prepared a nutritious meal with vegetables and lean protein.",
      partsOfSpeech: "adjective",
    },
    {
      en: "taste",
      bn: "রুচি",
      category: "food",
      explanation: "The sensation of flavor perceived in the mouth and throat on contact with a substance.",
      example: "The dish had a spicy taste.",
      partsOfSpeech: "noun",
    },
    {
      en: "cook",
      bn: "রান",
      category: "food",
      explanation: "Prepare (food, a dish, or a meal) by combining and heating the ingredients in various ways.",
      example: "She likes to cook Italian food.",
      partsOfSpeech: "verb",
    },
    {
      en: "bake",
      bn: "পাকা",
      category: "food",
      explanation: "Cook (food) by dry heat without direct exposure to a flame, typically in an oven or on a hot surface.",
      example: "They baked a cake for the birthday party.",
      partsOfSpeech: "verb",
    },
    {
      en: "grill",
      bn: "গ্রিল",
      category: "food",
      explanation: "Cook (food) using a grill, typically over direct heat.",
      example: "They grilled vegetables for dinner.",
      partsOfSpeech: "verb",
    },
  ];
  