import { Vocabulary } from "../types";

export const psychologyVocabularyArray: Vocabulary[] = [
    {
      en: "cognition",
      bn: "জ্ঞান",
      category: "psychology",
      explanation: "Cognition refers to mental processes involved in gaining knowledge and comprehension.",
      example: "Cognition includes processes like thinking, memory, and problem-solving.",
    },
    {
      en: "behavior",
      bn: "আচরণ",
      category: "psychology",
      explanation: "Behavior is the actions or reactions of an individual in response to external or internal stimuli.",
      example: "Psychologists study behavior to understand how people interact with their environment.",
    },
    {
      en: "emotion",
      bn: "ভাবাবেগ",
      category: "psychology",
      explanation: "Emotion is a complex psychological state that involves a subjective experience, a physiological response, and a behavioral response.",
      example: "Happiness is a positive emotion that can enhance well-being.",
    },
    {
      en: "personality",
      bn: "ব্যক্তিত্ব",
      category: "psychology",
      explanation: "Personality refers to the characteristic patterns of thoughts, feelings, and behaviors that make a person unique.",
      example: "Personality traits can influence how individuals react in different situations.",
    },
    {
      en: "motivation",
      bn: "প্রেরণা",
      category: "psychology",
      explanation: "Motivation is the process that initiates, guides, and maintains goal-oriented behaviors.",
      example: "Intrinsic motivation comes from within the individual rather than from external rewards.",
    },
    {
      en: "perception",
      bn: "ধারণা",
      category: "psychology",
      explanation: "Perception is the process of organizing and interpreting sensory information.",
      example: "Visual perception allows us to recognize objects and faces.",
    },
    {
      en: "therapy",
      bn: "থেরাপি",
      category: "psychology",
      explanation: "Therapy involves treatment methods aimed at improving mental health and well-being.",
      example: "Cognitive-behavioral therapy is effective for treating anxiety disorders.",
    },
    {
      en: "stress",
      bn: "চাপ",
      category: "psychology",
      explanation: "Stress is a physical and emotional response to challenging or threatening situations.",
      example: "Chronic stress can lead to health problems.",
    },
    {
      en: "anxiety",
      bn: "উদ্বেগ",
      category: "psychology",
      explanation: "Anxiety is a feeling of worry or fear, often about future events or situations.",
      example: "Anxiety disorders are among the most common mental health conditions.",
    },
    {
      en: "memory",
      bn: "মেমরি",
      category: "psychology",
      explanation: "Memory is the process by which information is encoded, stored, and retrieved.",
      example: "Short-term memory holds information temporarily for processing.",
    },
    {
      en: "learning",
      bn: "শেখা",
      category: "psychology",
      explanation: "Learning is the process of acquiring new knowledge or skills through experience or education.",
      example: "Learning theories explain how people acquire and retain knowledge.",
    },
    {
      en: "development",
      bn: "উন্নয়ন",
      category: "psychology",
      explanation: "Development refers to the growth and changes that occur throughout a person's life.",
      example: "Child development studies focus on cognitive and emotional growth.",
    },
    {
      en: "self-esteem",
      bn: "আত্মসম্মান",
      category: "psychology",
      explanation: "Self-esteem is an individual's overall subjective emotional evaluation of their own worth.",
      example: "High self-esteem is associated with positive mental health outcomes.",
    },
    {
      en: "unconscious",
      bn: "অবচেতন",
      category: "psychology",
      explanation: "The unconscious mind consists of thoughts and feelings not currently in conscious awareness.",
      example: "Freud proposed that the unconscious mind influences behavior.",
    },
    {
      en: "conditioning",
      bn: "শর্তায়ণ",
      category: "psychology",
      explanation: "Conditioning is a learning process in which an individual’s behavior becomes dependent on the occurrence of a stimulus.",
      example: "Classical conditioning involves learning through association.",
    },
    {
      en: "bias",
      bn: "পক্ষপাত",
      category: "psychology",
      explanation: "Bias is a tendency to think in a certain way that deviates from logical or rational thinking.",
      example: "Cognitive bias can affect decision-making processes.",
    },
    {
      en: "resilience",
      bn: "সহনশীলতা",
      category: "psychology",
      explanation: "Resilience is the ability to recover quickly from difficulties or setbacks.",
      example: "Building resilience can help individuals cope with stress.",
    },
    {
      en: "attachment",
      bn: "সংযুক্তি",
      category: "psychology",
      explanation: "Attachment is an emotional bond between individuals, often seen in caregiver-child relationships.",
      example: "Attachment theory explores the impact of early relationships on development.",
    },
    {
      en: "identity",
      bn: "পরিচয়",
      category: "psychology",
      explanation: "Identity is the qualities, beliefs, and expressions that make a person unique.",
      example: "Adolescents often explore their identity during their teenage years.",
    },
    {
      en: "empathy",
      bn: "সহানুভূতি",
      category: "psychology",
      explanation: "Empathy is the ability to understand and share the feelings of another person.",
      example: "Empathy plays a key role in social interactions and relationships.",
    },
  ];
  