import { Vocabulary } from "./types";

export const businessVocabularyArray: Vocabulary[] = [
  {
    en: "entrepreneur",
    bn: "উদ্যোক্তা",
    category: "business",
    explanation:
      "An entrepreneur is a person who starts, organizes, manages, and assumes the risks of a business.",
    example: "She is a successful entrepreneur who founded several tech startups.",
  },
  {
    en: "profit",
    bn: "লাভ",
    category: "business",
    explanation:
      "Profit is the financial gain made in a transaction or business venture after deducting all expenses.",
    example: "The company reported a significant profit margin this quarter.",
  },
  {
    en: "investment",
    bn: "বিনিয়োগ",
    category: "business",
    explanation:
      "Investment is the act of allocating resources, usually money, with the expectation of generating income or profit.",
    example: "His investment in the stock market paid off well.",
  },
  {
    en: "revenue",
    bn: "রাজস্ব",
    category: "business",
    explanation:
      "Revenue is the total income generated by a business from its sales and services.",
    example: "The company's revenue increased by 20% last year.",
  },
  {
    en: "market share",
    bn: "বাজার অংশীদারিত্ব",
    category: "business",
    explanation:
      "Market share refers to the portion of a market controlled by a particular company or product.",
    example: "The company aims to increase its market share in the electronics sector.",
  },
  {
    en: "brand",
    bn: "ব্র্যান্ড",
    category: "business",
    explanation:
      "A brand is a unique identity and image associated with a product or company.",
    example: "Apple is known for its strong brand and innovative products.",
  },
  {
    en: "merger",
    bn: "বিলীনকরণ",
    category: "business",
    explanation:
      "A merger is a combination of two companies to form a new entity.",
    example: "The merger between the two firms created a new market leader.",
  },
  {
    en: "acquisition",
    bn: "অধিগ্রহণ",
    category: "business",
    explanation:
      "An acquisition is the process of one company purchasing most or all of another company's shares to gain control.",
    example: "The acquisition of the startup boosted the company's technology capabilities.",
  },
  {
    en: "stakeholder",
    bn: "অংশীদার",
    category: "business",
    explanation:
      "A stakeholder is any individual or group affected by the activities of a business.",
    example: "Stakeholders include employees, customers, suppliers, and investors.",
  },
  {
    en: "liability",
    bn: "দায়বদ্ধতা",
    category: "business",
    explanation:
      "Liability refers to the company's legal debts or obligations arising from its business operations.",
    example: "The company has a liability of $1 million in loans.",
  },
  {
    en: "equity",
    bn: "ইক্যুইটি",
    category: "business",
    explanation:
      "Equity represents the ownership interest held by shareholders in a company.",
    example: "The equity in the business increased after the new investment.",
  },
  {
    en: "supply chain",
    bn: "সরবরাহ শৃঙ্খল",
    category: "business",
    explanation:
      "A supply chain is a network between a company and its suppliers to produce and distribute products.",
    example: "Optimizing the supply chain can reduce costs and improve efficiency.",
  },
  {
    en: "business plan",
    bn: "ব্যবসা পরিকল্পনা",
    category: "business",
    explanation:
      "A business plan is a formal document outlining the goals, strategies, and financial projections of a business.",
    example: "The entrepreneur presented her business plan to potential investors.",
  },
  {
    en: "cash flow",
    bn: "নগদ প্রবাহ",
    category: "business",
    explanation:
      "Cash flow refers to the total amount of money being transferred into and out of a business.",
    example: "Positive cash flow is essential for maintaining business operations.",
  },
  {
    en: "diversification",
    bn: "বৈচিত্র্যকরণ",
    category: "business",
    explanation:
      "Diversification is a strategy of expanding a company's product line or market presence.",
    example: "The company pursued diversification to mitigate risks.",
  },
  {
    en: "competitive advantage",
    bn: "প্রতিযোগিতামূলক সুবিধা",
    category: "business",
    explanation:
      "A competitive advantage is a condition that allows a company to produce goods or services better or more cheaply than its rivals.",
    example: "The unique design gives the brand a competitive advantage.",
  },
  {
    en: "franchise",
    bn: "ফ্র্যাঞ্চাইজি",
    category: "business",
    explanation:
      "A franchise is a type of business model where a franchisee pays to use the brand and business model of a franchisor.",
    example: "Owning a fast-food franchise can be a lucrative business opportunity.",
  },
  {
    en: "customer loyalty",
    bn: "গ্রাহক আনুগত্য",
    category: "business",
    explanation:
      "Customer loyalty refers to a customer's commitment to repurchase or continue using a brand's products or services.",
    example: "The loyalty program increased customer retention significantly.",
  },
  {
    en: "outsourcing",
    bn: "আউটসোর্সিং",
    category: "business",
    explanation:
      "Outsourcing is the practice of hiring external firms to handle business functions.",
    example: "Many companies outsource customer support to specialized firms.",
  },
  {
    en: "return on investment (ROI)",
    bn: "বিনিয়োগে ফেরত (ROI)",
    category: "business",
    explanation:
      "ROI measures the profitability of an investment relative to its cost.",
    example: "The marketing campaign yielded a high return on investment.",
  },
];