import { Vocabulary } from "./types";

export const politicsVocabularyArray: Vocabulary[] = [
    {
      en: "democracy",
      bn: "গণতন্ত্র",
      category: "politics",
      explanation: "A system of government by the whole population, typically through elected representatives.",
      example: "Democracy allows citizens to vote for their leaders.",
    },
    {
      en: "republic",
      bn: "গণরাজ্য",
      category: "politics",
      explanation: "A state in which supreme power is held by the people and their elected representatives.",
      example: "In a republic, the president is elected by the people.",
    },
    {
      en: "constitution",
      bn: "সংবিধান",
      category: "politics",
      explanation: "A set of fundamental principles or established precedents according to which a state is governed.",
      example: "The constitution outlines the rights of citizens.",
    },
    {
      en: "legislation",
      bn: "আইন প্রণয়ন",
      category: "politics",
      explanation: "Laws, considered collectively, that are enacted by a governing body.",
      example: "New legislation was passed to improve healthcare.",
    },
    {
      en: "governance",
      bn: "শাসন",
      category: "politics",
      explanation: "The process of making and enforcing decisions in a government.",
      example: "Good governance is essential for a country's development.",
    },
    {
      en: "ideology",
      bn: "ভাবধারা",
      category: "politics",
      explanation: "A system of ideas and ideals, especially one that forms the basis of economic or political theory.",
      example: "Political parties often base their policies on specific ideologies.",
    },
    {
      en: "campaign",
      bn: "প্রচার অভিযান",
      category: "politics",
      explanation: "An organized effort to win an election or influence a political decision.",
      example: "The candidate launched a campaign focusing on environmental issues.",
    },
    {
      en: "incumbent",
      bn: "বিদ্যমান",
      category: "politics",
      explanation: "The current holder of a political office.",
      example: "The incumbent mayor is running for re-election.",
    },
    {
      en: "partisanship",
      bn: "দলবাজি",
      category: "politics",
      explanation: "Strong, unwavering support for a particular political party.",
      example: "Partisanship often leads to political polarization.",
    },
    {
      en: "bipartisanship",
      bn: "দ্বিদলীয় সহযোগিতা",
      category: "politics",
      explanation: "Agreement or cooperation between two political parties that usually oppose each other.",
      example: "Bipartisanship is crucial for passing major legislation.",
    },
    {
      en: "constituency",
      bn: "নির্বাচনী এলাকা",
      category: "politics",
      explanation: "A body of voters in a specified area who elect a representative to a legislative body.",
      example: "The representative addressed the concerns of her constituency.",
    },
    {
      en: "diplomacy",
      bn: "কূটনীতি",
      category: "politics",
      explanation: "The art and practice of conducting negotiations between nations.",
      example: "Diplomacy can prevent conflicts between countries.",
    },
    {
      en: "sanction",
      bn: "নিষেধাজ্ঞা",
      category: "politics",
      explanation: "A threatened penalty for disobeying a law or rule, often used in international relations.",
      example: "Economic sanctions were imposed to pressure the government.",
    },
    {
      en: "sovereignty",
      bn: "সার্বভৌমত্ব",
      category: "politics",
      explanation: "The authority of a state to govern itself or another state.",
      example: "Sovereignty is a fundamental principle of international law.",
    },
    {
      en: "federalism",
      bn: "সংঘীয় ব্যবস্থা",
      category: "politics",
      explanation: "A system of government in which power is divided between a central authority and constituent units.",
      example: "Federalism allows states to have their own laws and policies.",
    },
    {
      en: "referendum",
      bn: "জনমত সংগ্রহ",
      category: "politics",
      explanation: "A general vote by the electorate on a single political question.",
      example: "The government held a referendum on constitutional changes.",
    },
    {
      en: "lobbying",
      bn: "লবিং",
      category: "politics",
      explanation: "The act of seeking to influence politicians or public officials on a particular issue.",
      example: "Lobbying efforts were made to change environmental policies.",
    },
    {
      en: "authoritarian",
      bn: "একনায়কতন্ত্র",
      category: "politics",
      explanation: "A governing system in which power is concentrated in the hands of a leader or small elite.",
      example: "Authoritarian regimes often restrict political freedoms.",
    },
    {
      en: "populism",
      bn: "জনতাবাদ",
      category: "politics",
      explanation: "A political approach that seeks to represent the interests of ordinary people.",
      example: "Populism often emerges during times of economic hardship.",
    },
    {
      en: "impeachment",
      bn: "অভিশংসন",
      category: "politics",
      explanation: "The process by which a legislative body brings charges against a government official.",
      example: "The president faced impeachment for misconduct.",
    },
  ];
  