import { Vocabulary } from "./types";

export const realEstateVocabulary: Vocabulary[] = [
  {
    en: "Property",
    bn: "সম্পত্তি",
    category: "Real Estate",
    explanation: "A piece of land and any structures on it.",
    example: "They bought a beautiful property in the countryside.",
    partsOfSpeech: "Noun",
  },
  {
    en: "Real Estate",
    bn: "অচল সম্পত্তি",
    category: "Real Estate",
    explanation: "Land and the buildings on it, considered as a commodity.",
    example: "The real estate market is booming in this city.",
    partsOfSpeech: "Noun",
  },
  {
    en: "Mortgage",
    bn: "বন্ধকী",
    category: "Real Estate",
    explanation: "A loan secured by real estate.",
    example: "They took out a mortgage to buy their first home.",
    partsOfSpeech: "Noun",
  },
  {
    en: "Rent",
    bn: "ভাড়া",
    category: "Real Estate",
    explanation: "A regular payment made for the use of a property.",
    example: "They pay rent to their landlord every month.",
    partsOfSpeech: "Noun/Verb",
  },
  {
    en: "Landlord",
    bn: "জমিদার",
    category: "Real Estate",
    explanation: "A person who owns and rents out property.",
    example: "The landlord raised their rent by 10%.",
    partsOfSpeech: "Noun",
  },
  {
    en: "Tenant",
    bn: "ভাড়াটে",
    category: "Real Estate",
    explanation: "A person who rents property.",
    example: "The tenants complained about the noisy neighbors.",
    partsOfSpeech: "Noun",
  },
  {
    en: "Lease",
    bn: "পট্টা",
    category: "Real Estate",
    explanation:
      "A legal agreement that grants the right to use a property for a specific period.",
    example: "They signed a lease for a two-year term.",
    partsOfSpeech: "Noun/Verb",
  },
  {
    en: "Down Payment",
    bn: "প্রাথমিক অর্থ প্রদান",
    category: "Real Estate",
    explanation: "A sum of money paid upfront when buying a property.",
    example: "They made a large down payment on their new home.",
    partsOfSpeech: "Noun",
  },
  {
    en: "Appraisal",
    bn: "মূল্যায়ন",
    category: "Real Estate",
    explanation: "An estimate of the value of a property.",
    example: "They got an appraisal before putting their house on the market.",
    partsOfSpeech: "Noun",
  },
  {
    en: "Realtor",
    bn: "রিয়েল এস্টেট এজেন্ট",
    category: "Real Estate",
    explanation: "A real estate agent who represents buyers or sellers.",
    example: "They hired a realtor to help them find a new home.",
    partsOfSpeech: "Noun",
  },
  {
    en: "Listing",
    bn: "তালিকাভুক্তি",
    category: "Real Estate",
    explanation: "A property that is being offered for sale or rent.",
    example: "They found their dream home on a real estate listing.",
    partsOfSpeech: "Noun",
  },
  {
    en: "Closing",
    bn: "সমাপ্তি",
    category: "Real Estate",
    explanation: "The final stage of a real estate transaction.",
    example: "The closing on their new home is scheduled for next week.",
    partsOfSpeech: "Noun",
  },
  {
    en: "Title",
    bn: "শিরোনাম",
    category: "Real Estate",
    explanation: "Legal proof of ownership of a property.",
    example: "They received the title to their new home after closing.",
    partsOfSpeech: "Noun",
  },
  {
    en: "Equity",
    bn: "ইকুইটি",
    category: "Real Estate",
    explanation: "The value of a property minus any outstanding debt.",
    example: "They have built up a lot of equity in their home over the years.",
    partsOfSpeech: "Noun",
  },
  {
    en: "Foreclosure",
    bn: "জবরদখল",
    category: "Real Estate",
    explanation:
      "The legal process of taking possession of a property due to non-payment of debt.",
    example:
      "They lost their home to foreclosure after falling behind on their mortgage payments.",
    partsOfSpeech: "Noun",
  },
  {
    en: "Property Taxes",
    bn: "সম্পত্তি কর",
    category: "Real Estate",
    explanation: "Taxes levied on the value of real estate.",
    example: "They pay property taxes to the local government every year.",
    partsOfSpeech: "Noun",
  },
  {
    en: "Zoning",
    bn: "জোনিং",
    category: "Real Estate",
    explanation: "Regulations that control the use of land and buildings.",
    example:
      "The zoning laws in this area restrict the construction of high-rise buildings.",
    partsOfSpeech: "Noun",
  },
  {
    en: "Condominium",
    bn: "কনডোমিনিয়াম",
    category: "Real Estate",
    explanation:
      "A building or complex of buildings where individual units are owned by residents.",
    example: "They live in a condominium in the city.",
    partsOfSpeech: "Noun",
  },
  {
    en: "Homeowner's Association (HOA)",
    bn: "গৃহোন্নয়ন সংস্থা",
    category: "Real Estate",
    explanation:
      "An organization that manages common areas and sets rules for residents in a condominium or planned community.",
    example: "The HOA regulates the use of the community pool and landscaping.",
    partsOfSpeech: "Noun",
  },
  {
    en: "Real Estate Investment Trust (REIT)",
    bn: "রিয়েল এস্টেট বিনিয়োগ ট্রাস্ট",
    category: "Real Estate",
    explanation:
      "A company that owns and operates income-producing real estate.",
    example: "They invested in a REIT that owns shopping malls.",
    partsOfSpeech: "Noun",
  },
];
