import { Vocabulary } from "./types";

export const travelVocabularyArray: Vocabulary[] = [
    {
      en: "travel",
      bn: "ভ্রমণ",
      category: "travel",
      explanation: "The action of traveling, typically for leisure, business, or exploration.",
      example: "She loves to travel to exotic destinations.",
    },
    {
      en: "tourism",
      bn: "পর্যটন",
      category: "travel",
      explanation: "The commercial organization and operation of vacations and visits to places of interest.",
      example: "Tourism contributes significantly to the economy of many countries.",
    },
    {
      en: "destination",
      bn: "গন্তব্য",
      category: "travel",
      explanation: "The place to which someone or something is going or being sent.",
      example: "Their dream destination is Paris.",
    },
    {
      en: "journey",
      bn: "প্রয়াণ",
      category: "travel",
      explanation: "An act of traveling from one place to another.",
      example: "The journey from New York to London took eight hours.",
    },
    {
      en: "adventure",
      bn: "সাহসিকতা",
      category: "travel",
      explanation: "An unusual and exciting or daring experience.",
      example: "They went on an adventure through the Amazon rainforest.",
    },
    {
      en: "explore",
      bn: "অন্বেষণ করা",
      category: "travel",
      explanation: "Travel in or through (an unfamiliar country or area) in order to learn about or familiarize oneself with it.",
      example: "They love to explore new cultures and cuisines.",
    },
    {
      en: "itinerary",
      bn: "মার্গনির্দেশিকা",
      category: "travel",
      explanation: "A planned route or journey.",
      example: "They planned their itinerary for the European tour.",
    },
    {
      en: "passport",
      bn: "পাসপোর্ট",
      category: "travel",
      explanation: "A document issued by a country to a citizen allowing that person to travel abroad and re-enter the home country.",
      example: "Make sure to carry your passport when traveling internationally.",
    },
    {
      en: "visa",
      bn: "ভিসা",
      category: "travel",
      explanation: "An endorsement on a passport indicating that the holder is allowed to enter, leave, or stay for a specified period of time in a country.",
      example: "You need a visa to enter many countries.",
    },
    {
      en: "hotel",
      bn: "হোটেল",
      category: "travel",
      explanation: "An establishment providing accommodations, meals, and other services for travelers and tourists.",
      example: "They booked a room at a luxurious hotel by the beach.",
    },
    {
      en: "reservation",
      bn: "আবাসন ক্রমানুযায়ী",
      category: "travel",
      explanation: "An arrangement whereby something, especially a seat or room, is booked or reserved for someone.",
      example: "They made a reservation at the restaurant for dinner.",
    },
    {
      en: "airport",
      bn: "বিমানবন্দর",
      category: "travel",
      explanation: "A complex of runways and buildings for the takeoff, landing, and maintenance of civil aircraft, with facilities for passengers.",
      example: "They arrived at the airport three hours before their flight.",
    },
    {
      en: "sightseeing",
      bn: "দর্শনার্থী",
      category: "travel",
      explanation: "The activity of visiting places of interest in a particular location.",
      example: "They spent the day sightseeing in Rome.",
    },
    {
      en: "culture",
      bn: "সংস্কৃতি",
      category: "travel",
      explanation: "The customs, arts, social institutions, and achievements of a particular nation, people, or other social group.",
      example: "They immersed themselves in the local culture during their travels.",
    },
    {
      en: "currency",
      bn: "মুদ্রা",
      category: "travel",
      explanation: "A system of money in general use in a particular country.",
      example: "They exchanged dollars for local currency upon arrival.",
    },
    {
      en: "tourist",
      bn: "পর্যটক",
      category: "travel",
      explanation: "A person who is traveling or visiting a place for pleasure.",
      example: "The city attracts millions of tourists each year.",
    },
    {
      en: "guide",
      bn: "গাইড",
      category: "travel",
      explanation: "A person who shows the way to others, especially one employed to show tourists around places of interest.",
      example: "Their guide provided insightful information about the historical landmarks.",
    },
    {
      en: "souvenir",
      bn: "স্মরণীয় ক্ষতি",
      category: "travel",
      explanation: "A thing that is kept as a reminder of a person, place, or event.",
      example: "They bought a beautiful souvenir from their trip.",
    },
    {
      en: "cruise",
      bn: "ক্রুজ",
      category: "travel",
      explanation: "A voyage on a ship or boat taken for pleasure or as a vacation and usually calling in at several places.",
      example: "They went on a Mediterranean cruise last summer.",
    },
    {
      en: "backpack",
      bn: "ব্যাগ",
      category: "travel",
      explanation: "A bag with shoulder straps that allow it to be carried on one's back, typically made of sturdy material and used to carry belongings while traveling.",
      example: "They packed everything they needed into their backpack for the hiking trip.",
    },
  ];
  